# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbackend.proto\x12\x07\x62\x61\x63kend\"!\n\x0cSetupRequest\x12\x11\n\tprocedure\x18\x01 \x01(\t\"1\n\rSetupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x10\n\x0e\x45xecuteRequest\"3\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10TerminateRequest\"5\n\x11TerminateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc3\x01\n\x07\x42\x61\x63kend\x12\x36\n\x05Setup\x12\x15.backend.SetupRequest\x1a\x16.backend.SetupResponse\x12<\n\x07\x45xecute\x12\x17.backend.ExecuteRequest\x1a\x18.backend.ExecuteResponse\x12\x42\n\tTerminate\x12\x19.backend.TerminateRequest\x1a\x1a.backend.TerminateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETUPREQUEST']._serialized_start=26
  _globals['_SETUPREQUEST']._serialized_end=59
  _globals['_SETUPRESPONSE']._serialized_start=61
  _globals['_SETUPRESPONSE']._serialized_end=110
  _globals['_EXECUTEREQUEST']._serialized_start=112
  _globals['_EXECUTEREQUEST']._serialized_end=128
  _globals['_EXECUTERESPONSE']._serialized_start=130
  _globals['_EXECUTERESPONSE']._serialized_end=181
  _globals['_TERMINATEREQUEST']._serialized_start=183
  _globals['_TERMINATEREQUEST']._serialized_end=201
  _globals['_TERMINATERESPONSE']._serialized_start=203
  _globals['_TERMINATERESPONSE']._serialized_end=256
  _globals['_BACKEND']._serialized_start=259
  _globals['_BACKEND']._serialized_end=454
# @@protoc_insertion_point(module_scope)
